[package]
name = "ddnet-log-anonymizer"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.3"
chrono = "0.4.40"
clap = { version = "4.5.31", features = ["derive"] }
indicatif = "0.17.11"
lazy_static = "1.5.0"
regex = "1.11.1"
